#!/bin/bash

#. /common.sh

echo "$(hostname -i) spark-master" >> /etc/hosts

sh /opt/spark/sbin/start-history-server.sh
/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --ip spark-master --port 7077 --webui-port 8080

